// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC484_Xnff5g8UpQq-AoJ4_Av35cL9JxHY',
    appId: '1:118794910708:web:daac4ad66733226a5a97a1',
    messagingSenderId: '118794910708',
    projectId: 'medsos-65342',
    authDomain: 'medsos-65342.firebaseapp.com',
    storageBucket: 'medsos-65342.firebasestorage.app',
    measurementId: 'G-0ZZSXHPPCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgLy347W100NYCKRnxSKM8OvEjfEdw_w',
    appId: '1:118794910708:android:eef4ee7986ceace95a97a1',
    messagingSenderId: '118794910708',
    projectId: 'medsos-65342',
    storageBucket: 'medsos-65342.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd495SiWS5UdHJu8vEUr3UstuxU6mZi90',
    appId: '1:118794910708:ios:d70405edfb509e205a97a1',
    messagingSenderId: '118794910708',
    projectId: 'medsos-65342',
    storageBucket: 'medsos-65342.firebasestorage.app',
    iosBundleId: 'com.example.medsos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd495SiWS5UdHJu8vEUr3UstuxU6mZi90',
    appId: '1:118794910708:ios:d70405edfb509e205a97a1',
    messagingSenderId: '118794910708',
    projectId: 'medsos-65342',
    storageBucket: 'medsos-65342.firebasestorage.app',
    iosBundleId: 'com.example.medsos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC484_Xnff5g8UpQq-AoJ4_Av35cL9JxHY',
    appId: '1:118794910708:web:ef8b4368a5a48f2b5a97a1',
    messagingSenderId: '118794910708',
    projectId: 'medsos-65342',
    authDomain: 'medsos-65342.firebaseapp.com',
    storageBucket: 'medsos-65342.firebasestorage.app',
    measurementId: 'G-XRYL9JJ4CW',
  );
}
